{
 "title": "Kafka Streams",
 "description": "Dashboard for a Kafka Streams application using Prometheus JMX-Exporter running in Kubernetes",
 "tags": [
  "Kafka-clients",
  "Kafka Streams"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "label_values(kafka_stream_alive_stream_threads{}, kubernetes_namespace)"
   },
   {
    "name": "kubernetes_service",
    "label": "Service",
    "query": "label_values(kafka_stream_alive_stream_threads{kubernetes_namespace=\"$kubernetes_namespace\"}, kubernetes_service)"
   },
   {
    "name": "kubernetes_pod",
    "label": "Pod",
    "query": "label_values(kafka_stream_alive_stream_threads{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\"}, kubernetes_pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active stream threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_stream_alive_stream_threads{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed stream threads since startup",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "kafka_stream_failed_stream_threads_total{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total consumed records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum (kafka_stream_topic_records_consumed_total{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"}) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total consumed records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum (kafka_stream_topic_records_consumed_total{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"}) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "The execution time in ms for processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "[ms]" } },
   "targets": [
    {
     "expr": "kafka_stream_thread_process_records_avg{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"} ",
     "legendFormat": "{{thread_id}}"
    },
    {
     "expr": "kafka_stream_thread_process_records_max{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"} ",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Processor nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "The end-to-end latency of a record in ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "[ms]" } },
   "targets": [
    {
     "expr": "avg(kafka_stream_processor_node_record_e2e_latency_avg{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"}) by (processor_node_id)",
     "legendFormat": "{{processor_node_id}}"
    },
    {
     "expr": "max(kafka_stream_processor_node_record_e2e_latency_max{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"}) by (processor_node_id)",
     "legendFormat": "{{thread_id}}"
    },
    {
     "expr": "min(kafka_stream_processor_node_record_e2e_latency_min{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"}) by (processor_node_id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}