{
 "title": "Kafka consumers",
 "description": "Kafka consumers",
 "tags": [
  "Kafka-clients",
  "Consumer"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "label_values(kafka_consumer_connection_count{}, kubernetes_namespace)"
   },
   {
    "name": "kubernetes_service",
    "label": "Service",
    "query": "label_values(kafka_consumer_connection_count{kubernetes_namespace=\"$kubernetes_namespace\"}, kubernetes_service)"
   },
   {
    "name": "kubernetes_pod",
    "label": "Pod",
    "query": "label_values(kafka_consumer_connection_count{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\"}, kubernetes_pod)"
   },
   {
    "name": "client_id",
    "label": "client_id",
    "query": "label_values(kafka_consumer_connection_count{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\"}, client_id)"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "label_values(kafka_consumer_fetch_manager_bytes_consumed_rate{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\", client_id=\"$client_id\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Commit rate",
   "type": "stat",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_rate{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average fetch throttle time",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_avg{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed auth rate",
   "type": "stat",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_failed_authentication_total{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rebalance rate per hour",
   "type": "stat",
   "description": "The number of total rebalance events per hour, both successful and unsuccessful rebalance attempts.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_rebalance_rate_per_hour{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"} + kafka_consumer_coordinator_failed_rebalance_rate_per_hour{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Consumer Commit Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Commit latency average",
   "type": "graph",
   "description": "The average time taken for a commit request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_latency_avg{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit rate",
   "type": "graph",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_rate{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Consumer Fetch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Fetch request rate",
   "type": "graph",
   "description": "The number of fetch requests per second.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_fetch_total{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch size avg",
   "type": "graph",
   "description": "The average number of bytes fetched per request for a topic",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_size_avg{topic=~\"$topic\", kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch latency average",
   "type": "graph",
   "description": "The average time taken for a fetch request.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Bytes consumed rate",
   "type": "graph",
   "description": "The average number of bytes consumed per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_bytes_consumed_total{topic=~\"$topic\", kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed",
   "type": "graph",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_records_consumed_total{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\", topic=\"$topic\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes consumed rate per topic",
   "type": "graph",
   "description": "The average number of bytes consumed per topic per second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_fetch_manager_bytes_consumed_total{topic!=\"\", kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed per topic",
   "type": "graph",
   "description": "The average number of records consumed per second per topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, kubernetes_pod) (rate(kafka_consumer_fetch_manager_records_consumed_total{topic!=\"\", kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}-{{topic}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Current connection count",
   "type": "graph",
   "description": "Number of simultaneous connections\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_connection_count{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node reponse rate",
   "type": "graph",
   "description": "response rate per node\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_node_response_rate{kubernetes_namespace=\"$kubernetes_namespace\", kubernetes_service=\"$kubernetes_service\", kubernetes_pod=\"$kubernetes_pod\",client_id=\"$client_id\"}"
    }
   ]
  }
 ]
}