spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      max-poll-records: ${KAFKA_MAX_POLL_RECORDS:1}
      properties:
        partition.assignment.strategy: ${KAFKA_PARTITION_ASSIGNMENT_STRATEGY:org.apache.kafka.clients.consumer.RangeAssignor, org.apache.kafka.clients.consumer.CooperativeStickyAssignor}
