apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-processor-scaler
  namespace: app
spec:
  scaleTargetRef:
    kind: Deployment
    name: app-processor
  pollingInterval: 20
  cooldownPeriod: 60
  minReplicaCount: 1
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: cluster-kafka-bootstrap.kafka.svc:9092
        consumerGroup: app-processor
        topic: app.lab.Bar
        lagThreshold: "100"
        offsetResetPolicy: earliest
