apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: app
  labels:
    deploymentName: app-processor
spec:
  scaleTargetRef:
    name: app-processor
  pollingInterval: 5
  cooldownPeriod: 20
  minReplicaCount: 1
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: cluster-kafka-bootstrap.kafka.svc:9092
        processorGroup: app-processor
        topic: app.lab.Bar
        # Optional
        lagThreshold: "10"
        offsetResetPolicy: latest
