apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-consumer-scaler
  namespace: app
spec:
  scaleTargetRef:
    kind: Deployment
    name: app-consumer
  pollingInterval: 5
  cooldownPeriod: 20
  minReplicaCount: 1
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: cluster-kafka-bootstrap.kafka.svc:9092
        consumerGroup: app-consumer
        topic: app.lab.Bar
        lagThreshold: "10"
        offsetResetPolicy: latest
