server:
  port: 8070

logging:
  level:
    root: ERROR
    ch.post: DEBUG
    org.apache.kafka: INFO
    org.springframework: WARN
    org.springframework.kafka: WARN

management:
  endpoint.health:
    show-details: always
    show-components: always
    probes.enabled: true
  security.enabled: false
  endpoints.web.exposure.include: '*'
  metrics:
    enable:
      jvm: true
    tags:
      application: ${spring.application.name}
spring:
  task:
    scheduling:
      pool:
        size: 50
  output:
    ansi:
      enabled: ALWAYS
  resources:
    cache:
      period: 0
    chain:
      enabled: true
      cache: false
  application:
    name: app-producer
  kafka:
    client-id: ${spring.application.name}
    bootstrap-servers: localhost:32000
    producer:
      acks: all
      properties:
        compression.type: lz4