apiVersion: apps/v1
kind: Deployment
metadata:
  name: strm-lag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strm-lag
  template:
    metadata:
      labels:
        app: strm-lag
    spec:
      containers:
        - name: strm-lag
          image: strm-lag:0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: "kubernetes"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: strm-lag
spec:
  selector:
    app: strm-lag
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer